### ISSUE TITLE
template using lake and mathlib4

### ISSUE THREAD

**Issue by 9glenda** [lenianiva/lean4-nix#1]
I think it would be useful to have a template using lake and mathlib4

**Comment by lenianiva** [comment]
For `lake`, do you just want it to be an executable in the devShell? Building a Lean package doesn't require lake.

For `mathlib4`, would it be a good idea to add it as a flake output? I don't use mathlib4 extensively in my projects. If the user demands a high degree of flexibility we could leave the management of mathlib to the user

**Comment by lenianiva** [comment]
Building `mathlib4` using a flake-like build maybe tough. I can try it though.

I suspect this will take a tool like `poetry2nix` or `crate2nix`, and we would have to parse the manifest to find dependencies. `buildLeanPackage` does not automatically deduce these dependencies.

**Comment by lenianiva** [comment]
> I'm pretty new to lean. For me the whole dependency handeling is a bit confusing. A example/template would be really useful for people starting out with lean.

I have an example here of using LSpec with a Lean library and executable: https://git.leni.sh/aniva/Pantograph/src/commit/2e1276c21c9a3c16cc8319b19b06d9e39571fb5e/flake.nix

There is currently no machinery for converting Lean dependencies in `lake-manifest.json` into Nix build paths, so supporting a dependency tree like Mathlib will require more work

**Comment by lenianiva** [comment]
It is done: https://github.com/lenianiva/lean4-nix/tree/main/templates/dependency

The example uses aesop, which has a secondary dependency `Batteries`.

I didn't use Mathlib as an example since it takes at least 30 min to build. Give it a shot.
